name: Check analyzer existence
description: Verifies that the Assembly Definition file does not have the reference to Analyzer.
runs: 
  using: composite
  steps:
      - uses: actions/checkout@v3
      - shell: bash
        run: |
          check () {
            result=`cat $1 | grep Analyzer`
            if [ ${#result} -ne 0 ]; then
              echo -e "\e[31m Error: '$1' includes the reference to Analyzer\e[m"
              exit 1
            fi
          }
          for file in `find . -name *.asmdef`
          do
            check $file
          done
