name: Check analyzer existence
description: Verifies that the Assembly Definition file does not have the reference to Analyzer.
runs: 
  using: composite
  steps:
      - shell: bash
        run: |
          check () {
            if [ `cat $1` == *Analyzer* ]; then
              echo -e "\e[31m Error: '$1' includes the reference to Analyzer\e[m"
              exit 1
            fi
          }
          for file in `find . -name *.asmdef`
          do
            check $file
          done
